dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: H4Btu/1DMO36B7yYE3/wm6GhQb+n7TUh2ZxYaJg1qXNyJHjt/QaFTQCbO8KEHqK10eiMK2wDpxKmZ94Gbbo1TJWwxihQb4ks3fotPp7zcGL5qMEfQ0tIUGVAw9F/ukg8GUWvqWTdE1LYk4XFW34yF3CuXjaX1eKLL02cKAfyIrlf8jmDU6QEEVyDJ3Pi0lmeA8MY9D/85MM0SFWE/SRYuZXpDQxXLTSMDk/vlUAZxvw/XNpzi3dwEbc9UQkk5fMuchD0cn8b8FwTE1m/2/PFgcVK7tDqRQMaNAxJ5vsqGWYCc5fGsTViAeddwndcXgzpPbBrFM4JU/1l/NEjDBvX0LOW3wh1TE3tmgqGk42AghukXQfKnx14JB4dG/mBNOx4TygZPLdPJbsVGEmdWh2lh1yLZgLb6D3QB9JCAVPFANM6bP6vkYsxyCe8ACuMIQnsXkl/R63DVlz/VC54YGpJbFsry8UuArA/AZn7NXzgc//mCawZAcsDhr7BFHftS4JnUc8RRgNEksUq441g1xz5rFX07ijVjbYtOckwGupSEQdcmrukA6QQizy3R05Gkz6udD6xI2vZYLXPTH4vN2+r5DlXnQw3tcxl1oiXGL5LYtXtGpGFkWds++uZKU4HbBusvY76mPnDc+rOOXPwGUMtkAAMpk4x4geT6Buu+Fz/WfE=
