dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
env:
  global:
    secure: T+J4aM9kmC6svqLH2lBN62xWnMv7JioJryNqUrhhS3/mSschbY1PupM4BnhTEgbN/XxEL8jQn42/k5gyz/wKJbXRd+NUAjOmwSVA2+HOGnUetnzyS0UHYjaI9tZJ/gU9yF25napS01CROo0G1SPPqzqoVxhHO7sQo0hSQvxhXvxeIKOyZokS+sVwKhPdtpNXinOGqv2mUCoI4Uq4ldFHciRKLa49HEbLCO0PwI/1NzUKLiZW7ZPL+Af2W54k+O1kzC9mjHl2Xi2bAxu3XSkRUC3AW3cyODgaLtuHHrxH1vVJ7qkYwe5bfNJ6BhSVq2bUDQbEJiC8ArVxorZPdOKp4dR4VHCG3+g2zlRghlYrYzdhm/iMyv75+iOktnMmQY/dWdSVob4vWhNz/4cC84bbWlMpd28HR7K7nV/9mrT9SXpZvK7nZq6DT+7cRvua54jqOo235aYuttDhFEm1Si7/KZNCJB0/nCUbc2N4sZys5bDs8lTpLjIgUa+ewrpjw0Ux1S4KE7TmjBSwwoMB7IwpBwgXRzi9km26vNVf05SWo9fWcVykXJnyInWh2w2qx0KkkGFuXHNKBI0XG78HzZj7eVxPuMm64HI3XfBu/HHrLzd9GkEAUK0WnjQcb9HkggsZmDguJuolyJnseHmQCK7tyhufVEHR71VLEJx0HGWHFSM=
