dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh |
  bash

install: ./install-dependencies.sh
script:
- mkdir -p /home/travis/.ssh/ ; touch /home/travis/.ssh/appuser.pub
- packer validate -var-file=packer/variables.json.example packer/app.json
- packer validate -var-file=packer/variables.json.example packer/db.json
- cd terraform/prod ; terraform init -backend=false ; terraform validate --var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd ../stage ; terraform init -backend=false ; terraform validate --var-file=terraform.tfvars.example
- tflint --var-file=terraform.tfvars.example
- cd ../../ansible ; ansible-lint playbooks/*.yml --exclude=roles/jdauphant.nginx

notifications:
  slack:
    rooms:
      secure: SiyOE/XawxAFcYEcLag/wE8PiaLHfJsrZ4tf8GLQQJUm4agM/Nkg0uC42jgGvlv0Qy7cZMi6a000HIPBp0bdezAA5hbtXcPFD/F/F+P/F67UJlzAoP5Tqa4bjwfOIwBuyofVUMfjdYrX8Exo6a0LUk0gECjnvG3AKDCItMxE2vFenTBeqebw1rQDysy2u30RYzuCACHDYS4lUGQFK27iAfCfn/lntHASIdmFXDO0zv0wwqg4TlR+DRNxsQqJ9P9Pasp/sSrWPVvhcl/BAL5SBYTW7WEq3Z78Y8mkofTQ8cBA/9ZXme8VOxb7uRKEqwNFYSwg2ucGh0eDOW5keRTkZaUq/f24ywRJpgLyud042KIts7ojvB0r02n9cARnH5fagxS03UOYP7YS+JF7H/+xvsfMjsEk5y1XW1qsU8jC8og5toSMCkpPF1z0OOkuAu09+ScooOBdGMHGZfwNwyLiTDLJWE0mDxmYhNrHvh471UJZiPnZUD2AWnuf3bd8UhY4lUV+V3wKfGh42R+S9OYsj7g5C3lgccseNHkQzILPXED8AKXeRYMUgkL98tsVVNMQXUPerJi/rbmWnLjG0F2bWrPmoGqCcT0cMj6yLTIAzUchEIw8hLW9g8BFPG9BzZ6nVhETAQ2XPLERGIOhAHgGrODU1/ZM258vvJiH6MTySNE=
